baseURL: http://www.ramantandon.com/
languageCode: en-us
title: Raman's Portfolio (Under development)
theme: "toha"

# Site parameters
params:
  # Set background image (free download - https://wallpaperaccess.com/4k-ultra-hd-technology) #3320201.jpg
  background: "images/background-image.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will default to the theme logos if not provided.
  logo:
    main: images/devops-logo.png
    inverted: images/devops-inverted-logo.png
    favicon: images/favicon.png

