baseURL: http://example.org/
languageCode: en-us
title: Raman's Portfolio (Under development)

# Site parameters

# Provide logos for your site. The inverted logo will be used in the initial
# transparent navbar and the main logo will be used in the non-transparent navbar.
# It will default to the theme logos if not provided.
params:
  logo:
    main: images/devops-logo.png
    inverted: images/devops-inverted-logo.png
    favicon: images/favicon.png

